# arguments for dataset
dataset: cityscapes
nclass: 19
crop_size: 769
data_root: data/cityscapes

# arguments for training
epochs: 240
batch_size: 1
lr: 0.005  # 8GPUs
lr_multi: 1.0
criterion:
  name: OHEM
  kwargs:
    ignore_index: 255
    thresh: 0.7
    min_kept: 100000
conf_thresh: 0.0
optim: SGD
# arguments for backbone
backbone: mit-b2
# arguments for decode head
decode_head: SegformerHead
in_channels: [64, 128, 320, 512]
channels: 256
