# arguments for dataset
dataset: pascal
nclass: 21
crop_size: 513
data_root: data/VOC

# arguments for training
epochs: 80
batch_size: 2
lr: 0.002  # 8GPUs
lr_multi: 10.0
criterion:
  name: CELoss
  kwargs:
    ignore_index: 255
conf_thresh: 0.0
t: 1.0
optim: SGD
# arguments for model
backbone: resnet101_dct_64
multi_grid: False
replace_stride_with_dilation: [False, False, True]

decode_head: DeepLabV3PlusHead
low_channels: 256
high_channels: 2048
dilations: [6, 12, 18]
